# Generated by Django 5.0 on 2024-04-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passward',
            new_name='password',
        ),
    ]
